name: Update Calendar Events

on:
  schedule:
    # Run daily at 6:00 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run calendar script
      run: python fetch_calendar.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add index.html
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update calendar events - $(date +'%Y-%m-%d %H:%M:%S UTC')" && git push)
